name: Flutter Web
on:
  push:
    branches:
      - master

  jobs:
    build:
      name: Build App and Deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: subosito/flutter-action@v1
          with:
           flutter-version: '2.8.1'
           channel: 'stable'
        - run: flutter build web --release

