name: Flutter Web
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Web and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
      - run: flutter build web --release